Add 0.54.x features to docs
navidrome/website pull request #185
Opened 2024-12-22 00:09 UTC by Szeraax

2024-12-22 00:24 UTC, kgarner7 requested changes

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +**Configuration File**: After installation, Navidrome MUST be configured to run. The default path for the configuration file is /var/lib/navidrome/navidrome.toml. Create and edit the file using nano
`/etc/navidrome/navidrome.toml`

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +apt install ./navidrome_0.XX.X_linux_amd64.deb
`sudo apt install`

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +sudo systemctl enable navidrome
You could also combine this as `sudo systemctl enable --now navidrome`

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +
Add get logs: `sudo journalctl -u navidrome` (`-n` lines, `-f` for live)

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +
Note that the default music path is `/opt/navidrome/music`, and that it is running as user `navidrome`

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +BackupSchedule = "0 0 * * *"
Please use the proper values from https://www.navidrome.org/docs/usage/configuration-options/#:~:text=album%2Fartist.*%2C%20external-,backup.path,-ND_BACKUP_PATH

Note that count is required (all three properties are required)

As a nested toml example
```toml
[Backup]
Path = "/path/to/backup/folder"
Count = 5
Schedule =  "0 0 * * *"
```

Or `Backup.Path`. Also please not it in docker

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +By following this guide, you can effectively set up and manage backups for your Navidrome music server, ensuring your data is protected and easily recoverable.
Note that you can manually backup `navidrome backup`, and to restore, you need to do `navidrome restore` **when the system is not running**.

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +Navidrome version 0.54.x introduces a backup feature that allows you to safeguard your music server's data. This guide will walk you through configuring backups using both the config.toml file and en
Note that it just backs up the database (not music). And probably also note the file names, and count.

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +Using `dpkg`:
Also add a section for rpm-based?

2024-12-22 00:24 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +* **Permissions**: Ensure that the user running Navidrome has the necessary permissions to access your music library.
Probably note again here that the user is `navidrome` (the deb/rpm creates a `navidrome` user)

2024-12-22 04:17 UTC, Szeraax commented on content/en/docs/Installation/linux.md
> +
Adding this note to the MusicFolder section above.

2024-12-22 04:17 UTC, Szeraax commented on content/en/docs/Installation/linux.md
> +Using `dpkg`:
Good idea.

2024-12-22 04:17 UTC, Szeraax commented on content/en/docs/Usage/backup.md
> +BackupSchedule = "0 0 * * *"
Why did Gurubase do me so wrong! LOL. It was supposed to give me good stuff from the config options. Working on it!

2025-01-12 03:14 UTC, kgarner7 requested changes
Some more changes. Let me know if you need help with those.

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +Restore a backup by running the `navidrome backup restore` command.
Provide fill example (need to specify path). Emphasize **strongly** that this should not be done on a live system

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +
Provide note that for systemd, if not in `/var/lib/navidrome`, you may need to add the path to read write path

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +~~~
Note that:
1. Manual backup ignores the backup count (this is by design)
2. You can manually prune (using `navidrome backup prune`)

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +sudo docker compose run <service_name> backup create
`sudo docker compose run <service name> /app/navidrome backup create`, I believe?

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
>  WorkingDirectory=/var/lib/navidrome
Potentially also note here, that you may need to update systemd service if backup is somewhere else

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +Using `dpkg`:
Any plans for this follow-up?

2025-01-12 03:14 UTC, kgarner7 commented on content/en/docs/Installation/linux.md
> +
If using deb/rpm, these are already filled in. Probably say instead of "add" change (or add, if bare metal)

2025-01-12 04:37 UTC, Szeraax commented on content/en/docs/Installation/linux.md
> +Using `dpkg`:
I haven't tried setting up a rpm distro, haven't decided if I'm going to or not. If someone else wants to tackle actually doing the installation for this section, that would be great.

2025-01-12 05:21 UTC, Szeraax commented on content/en/docs/Usage/backup.md
> +Restore a backup by running the `navidrome backup restore` command.
Ok, now that I have tested the restore with pr-3579 in place which requires the backup name, I get prompted to create a super admin on first start. Is that intentional? I see my other users also do not get restored, so all play counts are lost as well. Earlier in this doc, I call out that users and play counts are supposed to be part of the backup so I need to know if I'm hitting a bug or if I need to go edit the doc and state that users and play counts are NOT part of the restore process.

2025-01-12 05:27 UTC, Szeraax commented on content/en/docs/Usage/backup.md
> +
Is it fair to say that that ONLY applies to linux installations? manual, rpm, and deb? Or could systemd ever need configured for containerized ND services? I'm thinking I'd like to either put the notes on linux systems that run ND through systemd as part of the "Additional Considerations" at the bottom or create a separate section dedicated to it.

2025-01-12 05:34 UTC, Szeraax commented on content/en/docs/Usage/backup.md
> +~~~
Called out that multiple backups will be cleaned up down to the backup count setting.

2025-01-12 05:55 UTC, Szeraax commented on content/en/docs/Usage/backup.md
> +sudo docker compose run <service_name> backup create
Works fine on my container service (I think maybe the container entry point is already /app/navidrome?): 

![image](https://github.com/user-attachments/assets/d581e9a6-c73a-4582-b434-f6e0920474e8)

2025-01-12 05:58 UTC, Szeraax commented on content/en/docs/Installation/linux.md
>  WorkingDirectory=/var/lib/navidrome
Going to leave this open for now and link to exact spot where that documentation lives once its in place.

2025-01-12 06:01 UTC, Szeraax commented on content/en/docs/Installation/linux.md
> +
Hopefully with this change, users will be able to figure out whether they are needing to update or add that setting.

2025-01-12 06:54 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +
Yes, only bare metal

2025-01-12 06:55 UTC, kgarner7 commented on content/en/docs/Usage/backup.md
> +Restore a backup by running the `navidrome backup restore` command.
That's definitely a failed restore. `navidrome backup restore -b $PATH_TO_BACKUP` is supposed to restore everything as-is.
1. Did you do it while Navidrome was running?
2. Were there existing `*-shm` / `--wal` files?
Can diagnose further in Discord

2025-03-11 00:18 UTC, merged